import { useState } from "react";
import Head from "next/head";
import Footer from "../components/Footer";
import InCommon from "../components/InCommon";
import MapsAndSet from "../components/MapsAndSet";
export default function Home() {
  const [count, setCount] = useState(1);
  const mapsAndSetDetails = [
    "Maps: Holds key-value pairs, the key can be any data type.",
    "Map remembers the original insertion order of the keys.",
    "Can use `size` to get the number of Map elements.",
    "Ordering: Keys are ordered based off of when they were added to the Map (similar to array).",
    "Iterating: Maps have a built in iterator. Which means you can use methods like `forEach`.",
    "Length: Use size property.",
    "Performance: Maps are designed w/ functionality of being a lookup table / dictionary.",
    "Great choice for adding & removing of key/value pairs.",
  ];
  return (
    <div className="p-4">
      <style jsx>{`
        .main {
          min-height: 85vh;
          padding: 4rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }
      `}</style>
      <Head>
        <title>State &amp; Props</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        {/* <InCommon
          title="Do We Have Anything In Common?"
          description="Checks both arrays, returns true if they have an element has a shared value."
        /> */}
        <MapsAndSet title="Maps &amp; Sets" descriptions={mapsAndSetDetails} />
      </div>
      <Footer />
    </div>
  );
}
